
estados_brasileiros = {
    'AC': 'acre',
    'AL': 'alagoas',
    'AP': 'amapa',
    'AM': 'amazonas',
    'BA': 'bahia',
    'CE': 'ceara',
    'DF': 'distrito_federal',
    'ES': 'espirito_santo',
    'GO': 'goias',
    'MA': 'maranhao',
    'MT': 'mato_grosso',
    'MS': 'mato_grosso_do_sul',
    'MG': 'minas_gerais',
    'PA': 'para',
    'PB': 'paraiba',
    'PR': 'parana',
    'PE': 'pernambuco',
    'PI': 'piaui',
    'RJ': 'rio_de_janeiro',
    'RN': 'rio_grande_do_norte',
    'RS': 'rio_grande_do_sul',
    'RO': 'rondonia',
    'RR': 'roraima',
    'SC': 'santa_catarina',
    'SP': 'sao_paulo',
    'SE': 'sergipe',
    'TO': 'tocantins'
}